[package]
name = "functional_functions"
version = "0.1.0"
authors = ["Jonathan Smith <nz.jaybird@gmail.com>"]
edition = "2018"

[dependencies]
nom = "^4.0"
clap = { version = "2.32", features = ["yaml"] }
